# basic parameters
checkpoint_dir: 'checkpoint'
model_path: 'checkpoint/baseline4_large/checkpoint/best_dev'
name: 'baseline4_large_test'
gpu: 0
per_gpu_batch_size: 4
seed: 0

# evaluation parameters
eval_data: 'data/test.json'
write_results: true

# model specific parameters
n_context: 3
text_maxlength: 250
no_sent: false
no_path: false
duplicate_sample: true