# basic parameters
checkpoint_dir: 'checkpoint'
name: 'baseline5_large'
gpu: 1
per_gpu_batch_size: 4
seed: 0

# training parameters
train_data: 'data/train.json'
eval_data: 'data/dev.json'
eval_freq: 5000

# optim parameters
epochs: 20
early_stop_count: 20
# total_steps: 70000

# model specific parameters
model_size: 'large'
n_context: 5
text_maxlength: 250
no_sent: false
no_path: false
duplicate_sample: true